USE master;

IF NOT EXISTS(SELECT * FROM sys.databases WHERE name = 'ToDo')
BEGIN 
	CREATE DATABASE ToDo;
END
GO

USE ToDo;

IF EXISTS( SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Category')
BEGIN
	IF EXISTS( SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ToDoItem')
	BEGIN
		DROP TABLE ToDoItem
	END

	DROP TABLE Category
END

CREATE TABLE Category (
	CategoryId INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Name NVARCHAR(10) NOT NULL,
	CreatedOn DATETIME DEFAULT GETDATE(),
	ModifiedOn DATETIME DEFAULT GETDATE()
);

INSERT INTO Category (Name)
VALUES ('Call'),
		('Cook'),
		('Daily'),
		('Date'),
		('Gar'),
		('Go'),
		('Hw'),
		('Out'),
		('Pw'),
		('Sys');

		
IF EXISTS( SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Who')
BEGIN
	IF EXISTS( SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ToDoItem')
	BEGIN
		DROP TABLE ToDoItem
	END

	DROP TABLE Who
END

CREATE TABLE Who (
	WhoId INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Name NVARCHAR(10) NOT NULL,
	CreatedOn DATETIME DEFAULT GETDATE(),
	ModifiedOn DATETIME DEFAULT GETDATE()
);

INSERT INTO Who (Name)
VALUES ('Beth'),
       ('David'),
	   ('Us')
	   
IF EXISTS( SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ToDoItem')
BEGIN
	DROP TABLE ToDoItem
END

CREATE TABLE ToDoItem (
	Id BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Name NVARCHAR(25) NULL,
	ItemDate Date NULL,
	Who INT FOREIGN KEY REFERENCES Who (WhoId),
	Category INT FOREIGN KEY REFERENCES Category (CategoryId),
	Status NVARCHAR(25) NULL,
	Cost INT NULL,
	Notes NVARCHAR(50) NULL,
	Done BIT DEFAULT 0,
	CreatedOn DATETIME DEFAULT GETDATE(),
	ModifiedOn DATETIME DEFAULT GETDATE()
)

INSERT INTO ToDoItem (Name, ItemDate, Who, Category, Status, Cost, Notes, Done)
SELECT 'ToDo Item', GETDATE(), 1,1,'Status',1,'Notes',0;

INSERT INTO ToDoItem (Name, ItemDate, Who, Category, Status, Cost, Notes, Done)
SELECT 'Done Item', GETDATE(), 1,1,'Status',1,'Notes',1;

SELECT * FROM ToDoItem;