name: Release Workflow

on:
  push:
    tags:
      - v*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run build
        run: npm run build:win
      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_title: ${{ github.ref_name }}
          body: Updated to version ${{ github.ref_name }}
          draft: false
          prerelease: false
      - name: Upload Asset
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/better_todo-${{ github.ref_name }}-setup.exe
          asset_name: your_file.zip
          asset_content_type: application/zip
          
