name: Release Workflow

on:
  push:
    tags:
      - v*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run build
        run: npm run build:win
      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_title: ${{ github.ref_name }}
          body: Updated to version ${{ github.ref_name }}
          draft: false
          prerelease: false
          assets:
            - dist/*.exe
